### ISSUE TITLE
Aspose-Crack,Aspose转pdf去水印方法 | Perhamer's blog

### ISSUE THREAD

**Issue by perhamer** [perhamer/GIT_TALK#3]
https://blog.perhamer.com/page/20y5m8s01.html 

 aspose是一个比较稳定快速的office转pdf的插件，但是试用版会自动在pdf上加水印，下附去水印教程，急用的同学可以到文章底部下载：

**Comment by yys970601** [comment]
厉害了

**Comment by qvyue** [comment]
最新的Aspose.Word好像破解不了，版本是 aspose-words-21.5.0-jdk17.jar
```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at com.aspose.words.zzZ85.zzZ(Unknown Source)
	at com.aspose.words.zzZ85.zzXg(Unknown Source)
	at com.aspose.words.zzZ81.zzXE(Unknown Source)
	at com.aspose.words.Document.zzY(Unknown Source)
	at com.aspose.words.Document.zzZ(Unknown Source)
	at com.aspose.words.Document.<init>(Unknown Source)
	at com.aspose.words.Document.<init>(Unknown Source)
	at com.qvyue.asposewords2110java.AsposeTest.main(AsposeTest.java:7)
Caused by: java.lang.IllegalArgumentException: bytes cannot be null
	at com.aspose.words.internal.zz1B.zzZp(Unknown Source)
	at com.aspose.words.zzZ87.<init>(Unknown Source)
	at com.aspose.words.zzZ87.<clinit>(Unknown Source)
	... 8 more
```

**Comment by Leon-Fan** [comment]
aspose-pdf什么时候更新下呀

**Comment by SnowflyW** [comment]
aspose-imaging有空破解下呀
